### ISSUE TITLE
Review 1

### ISSUE THREAD

**Issue by santiagobasulto** [aler785/Fifa#1]
Hello Alessandro! The project is looking great so far! All the charts (including the radial) look very good and contain the right information.

The one thing to improve is: **tell me a story** Your current notebook is just a bunch of code with charts mixed within it. You need to make the data tell us your story, or what you're trying us to understand. Use the notebooks markdown features to add information about the charts you're doing and why/how you're doing them.

Try to minimize the "code" to a minimum, for example, this doesn't add much:
![image](https://user-images.githubusercontent.com/872296/59766194-00e03280-9276-11e9-87c4-b4f70da50f14.png)

Something that might help is moving all the utility functions to a separate module and importing that module at the top.

The objective should be to show this to someone that has 0 experience with coding.

**Comment by aler785** [comment]
Ok adjusted
